if(NOT DEFINED OUTPUT_FILE OR OUTPUT_FILE STREQUAL "")
    message(FATAL_ERROR "GenerateEmbeddedSpirvHeader.cmake requires -DOUTPUT_FILE=<path>.")
endif()

if(NOT DEFINED SPV_FILES OR SPV_FILES STREQUAL "")
    message(FATAL_ERROR "GenerateEmbeddedSpirvHeader.cmake requires -DSPV_FILES=<list>.")
endif()

set(_spv_files ${SPV_FILES})
list(LENGTH _spv_files _spv_count)
if(_spv_count EQUAL 0)
    message(FATAL_ERROR "No SPIR-V files provided to GenerateEmbeddedSpirvHeader.cmake.")
endif()

get_filename_component(_out_dir "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${_out_dir}")

set(_header "/* Auto-generated. Do not edit by hand. */\n")
string(APPEND _header "#pragma once\n")
string(APPEND _header "#include <cstddef>\n")
string(APPEND _header "#include <cstdint>\n")
string(APPEND _header "#include <cstring>\n\n")
string(APPEND _header "namespace exynostools_embedded_spirv {\n\n")
string(APPEND _header "struct ShaderBlob {\n")
string(APPEND _header "    const uint32_t* words;\n")
string(APPEND _header "    size_t word_count;\n")
string(APPEND _header "    const char* name;\n")
string(APPEND _header "};\n\n")

set(_blob_entries "")

foreach(_spv IN LISTS _spv_files)
    if(NOT EXISTS "${_spv}")
        message(FATAL_ERROR "SPIR-V file not found: ${_spv}")
    endif()

    get_filename_component(_shader_name "${_spv}" NAME)
    string(MAKE_C_IDENTIFIER "${_shader_name}" _shader_ident)

    file(READ "${_spv}" _hex HEX)
    string(LENGTH "${_hex}" _hex_len)
    math(EXPR _hex_rem "${_hex_len} % 8")
    if(NOT _hex_rem EQUAL 0)
        message(FATAL_ERROR "SPIR-V file is not word-aligned: ${_spv}")
    endif()

    math(EXPR _word_count "${_hex_len} / 8")
    math(EXPR _last_word "${_word_count} - 1")

    string(APPEND _header "alignas(4) static const uint32_t ${_shader_ident}_words[] = {\n")
    set(_line "    ")
    foreach(_idx RANGE 0 ${_last_word})
        math(EXPR _off "${_idx} * 8")
        string(SUBSTRING "${_hex}" ${_off} 8 _chunk)
        string(SUBSTRING "${_chunk}" 0 2 _b0)
        string(SUBSTRING "${_chunk}" 2 2 _b1)
        string(SUBSTRING "${_chunk}" 4 2 _b2)
        string(SUBSTRING "${_chunk}" 6 2 _b3)
        set(_word "0x${_b3}${_b2}${_b1}${_b0}u")

        if(_idx EQUAL _last_word)
            set(_sep "")
        else()
            set(_sep ",")
        endif()

        string(APPEND _line "${_word}${_sep} ")
        math(EXPR _next "${_idx} + 1")
        math(EXPR _mod "${_next} % 6")
        if(_mod EQUAL 0 OR _idx EQUAL _last_word)
            string(APPEND _header "${_line}\n")
            set(_line "    ")
        endif()
    endforeach()

    string(APPEND _header "};\n")
    string(APPEND _header "static constexpr size_t ${_shader_ident}_word_count = sizeof(${_shader_ident}_words) / sizeof(${_shader_ident}_words[0]);\n")
    string(APPEND _header "static constexpr ShaderBlob ${_shader_ident}_blob{${_shader_ident}_words, ${_shader_ident}_word_count, \"${_shader_name}\"};\n\n")

    if(_blob_entries STREQUAL "")
        set(_blob_entries "    ${_shader_ident}_blob")
    else()
        string(APPEND _blob_entries ",\n    ${_shader_ident}_blob")
    endif()
endforeach()

string(APPEND _header "static constexpr ShaderBlob kShaderBlobs[] = {\n${_blob_entries}\n};\n\n")
string(APPEND _header "inline const ShaderBlob* find_shader_blob(const char* shader_name) {\n")
string(APPEND _header "    if (!shader_name) {\n")
string(APPEND _header "        return nullptr;\n")
string(APPEND _header "    }\n")
string(APPEND _header "    for (const ShaderBlob& blob : kShaderBlobs) {\n")
string(APPEND _header "        if (std::strcmp(blob.name, shader_name) == 0) {\n")
string(APPEND _header "            return &blob;\n")
string(APPEND _header "        }\n")
string(APPEND _header "    }\n")
string(APPEND _header "    return nullptr;\n")
string(APPEND _header "}\n\n")
string(APPEND _header "}  // namespace exynostools_embedded_spirv\n")

file(WRITE "${OUTPUT_FILE}" "${_header}")
