name: build-android-arm64

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake ninja-build meson zstd python3-pip
          pip3 install meson ninja

      - name: Setup Android NDK r25b
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b

      - name: Configure (CMake Android arm64)
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          cmake -S . -B build-android \
            -DCMAKE_TOOLCHAIN_FILE="${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=31 \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build (CMake)
        run: cmake --build build-android --config Release -j

      - name: Install to staging
        run: cmake --install build-android --prefix $(pwd)/staging

      - name: Verify size
        run: |
          ls -lh staging/usr/lib/
          sofile=staging/usr/lib/libxeno_wrapper.so
          if [ ! -f "$sofile" ]; then echo "Missing libxeno_wrapper.so"; exit 1; fi
          size=$(stat -c%s "$sofile")
          echo "Size: $size bytes"
          if [ "$size" -lt 80000 ]; then echo "Shared object too small (<80KB)"; exit 1; fi

      - name: Prepare package layout
        run: |
          mkdir -p pkg/usr/lib pkg/usr/share pkg/etc/exynostools pkg/profiles/winlator pkg/assets/shaders/decode
          cp -v staging/usr/lib/libxeno_wrapper.so pkg/usr/lib/
          cp -v usr/share/meta.json pkg/usr/share/
          cp -v etc/exynostools/performance_mode.conf pkg/etc/exynostools/
          cp -v profiles/winlator/*.env pkg/profiles/winlator/
          cp -v assets/shaders/decode/*.spv pkg/assets/shaders/decode/

      - name: Create tar.zst
        run: |
          tar --zstd -cvf exynostools-android-arm64.tar.zst -C pkg .
          echo "Created exynostools-android-arm64.tar.zst"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exynostools-android-arm64
          path: exynostools-android-arm64.tar.zst

